version: '3.7'

services:

  hexagonal-db:
    container_name: hexagonal-db
    image: mysql:5.7.17
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hexagonal
    ports:
      - 3336:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    volumes:
      - hexagonal-db-volume:/var/lib/mysql

volumes:
  hexagonal-db-volume:
    name: hexagonal-db-volume
